version: '3'

services:

  numbers-service:
    build:
      context: .
      dockerfile: build/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      profile:  local
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: unumbers
      POSTGRES_PASSWORD: cc402fd0
      POSTGRES_DB: numbers
    ports:
      - "5432:5432"