#
# Server
#
SERVER_PORT: 8080
#
# Database
#
DB_HOST: postgres
DB_PORT: 5432
DB_NAME: numbers
DB_USER: unumbers
DB_PASSWORD: cc402fd0
DB_SSLMODE: disable
#
# Swagger
#
SWAGGER_USER: numbers
SWAGGER_PASSWORD: d081da90622a
